In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/ds_infosys/HTRU_2.csv')
df.head()

,Mean,Std_deviation,Excess_kurtosis,Skewness,Mean_dmsnr,Std_deviation_dmsnr,Excess_kurtosis_dmsnr,Skewness_dmsnr,Class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [3]:
df.tail()

,Mean,Std_deviation,Excess_kurtosis,Skewness,Mean_dmsnr,Std_deviation_dmsnr,Excess_kurtosis_dmsnr,Skewness_dmsnr,Class
17893,136.429688,59.847421,-0.187846,-0.738123,1.296823,12.166062,15.450260,285.931022,0
17894,122.554688,49.485605,0.127978,0.323061,16.409699,44.626893,2.945244,8.297092,0
17895,119.335938,59.935939,0.159363,-0.743025,21.430602,58.872000,2.499517,4.595173,0
17896,114.507812,53.902400,0.201161,-0.024789,1.946488,13.381731,10.007967,134.238910,0
17897,57.062500,85.797340,1.406391,0.089520,188.306020,64.712562,-1.597527,1.429475,0

In [5]:
df[df['Class']==1]

,Mean,Std_deviation,Excess_kurtosis,Skewness,Mean_dmsnr,Std_deviation_dmsnr,Excess_kurtosis_dmsnr,Skewness_dmsnr,Class
19,99.367188,41.572202,1.547197,4.154106,27.555184,61.719016,2.208808,3.662680,1
42,120.554688,45.549905,0.282924,0.419909,1.358696,13.079034,13.312141,212.597029,1
61,27.765625,28.666042,5.770087,37.419009,73.112876,62.070220,1.268206,1.082920,1
92,23.625000,29.948654,5.688038,35.987172,146.568562,82.394624,-0.274902,-1.121848,1
93,94.585938,35.779823,1.187309,3.687469,6.071070,29.760400,5.318767,28.698048,1
...,...,...,...,...,...,...,...,...,...
17515,89.867188,47.482295,1.591325,2.505057,0.763378,12.393561,17.940745,333.902630,1
17529,27.039062,33.754722,4.779124,26.255357,129.863712,78.815440,-0.348492,-0.893791,1
17558,77.070312,39.000638,1.884421,6.372178,38.517559,65.741059,1.589513,1.285346,1
17642,28.375000,27.649311,6.377273,45.944048,141.860368,82.893017,-0.477222,-1.067880,1
17876,111.765625,52.943585,0.671724,0.383594,149.843646,97.926948,-0.696153,-1.260403,1

In [10]:
df.isnull().sum()

Mean                     0
Std_deviation            0
Excess_kurtosis          0
Skewness                 0
Mean_dmsnr               0
Std_deviation_dmsnr      0
Excess_kurtosis_dmsnr    0
Skewness_dmsnr           0
Class                    0
dtype: int64

In [11]:
df.describe()

,Mean,Std_deviation,Excess_kurtosis,Skewness,Mean_dmsnr,Std_deviation_dmsnr,Excess_kurtosis_dmsnr,Skewness_dmsnr,Class
count,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000
mean,111.079968,46.549532,0.477857,1.770279,12.614400,26.326515,8.303556,104.857709,0.091574
std,25.652935,6.843189,1.064040,6.167913,29.472897,19.470572,4.506092,106.514540,0.288432
min,5.812500,24.772042,-1.876011,-1.791886,0.213211,7.370432,-3.139270,-1.976976,0.000000
25%,100.929688,42.376018,0.027098,-0.188572,1.923077,14.437332,5.781506,34.960504,0.000000
50%,115.078125,46.947479,0.223240,0.198710,2.801839,18.461316,8.433515,83.064556,0.000000
75%,127.085938,51.023202,0.473325,0.927783,5.464256,28.428104,10.702959,139.309330,0.000000
max,192.617188,98.778911,8.069522,68.101622,223.392141,110.642211,34.539844,1191.000837,1.000000

In [12]:
cor = df.corr()#correlation matrix
print(cor)

                           Mean  Std_deviation  Excess_kurtosis  Skewness  \
Mean                   1.000000       0.547137        -0.873898 -0.738775
Std_deviation          0.547137       1.000000        -0.521435 -0.539793
Excess_kurtosis       -0.873898      -0.521435         1.000000  0.945729
Skewness              -0.738775      -0.539793         0.945729  1.000000
Mean_dmsnr            -0.298841       0.006869         0.414368  0.412056
Std_deviation_dmsnr   -0.307016      -0.047632         0.432880  0.415140
Excess_kurtosis_dmsnr  0.234331       0.029429        -0.341209 -0.328843
Skewness_dmsnr         0.144033       0.027691        -0.214491 -0.204782
Class                 -0.673181      -0.363708         0.791591  0.709528

                       Mean_dmsnr  Std_deviation_dmsnr  Excess_kurtosis_dmsnr  \
Mean                    -0.298841            -0.307016               0.234331
Std_deviation            0.006869            -0.047632               0.029429
Excess_kurtosis          0.414368             0.432880              -0.341209
Skewness                 0.412056             0.415140              -0.328843
Mean_dmsnr               1.000000             0.796555              -0.615971
Std_deviation_dmsnr      0.796555             1.000000              -0.809786
Excess_kurtosis_dmsnr   -0.615971            -0.809786               1.000000
Skewness_dmsnr          -0.354269            -0.575800               0.923743
Class                    0.400876             0.491535              -0.390816

                       Skewness_dmsnr     Class
Mean                         0.144033 -0.673181
Std_deviation                0.027691 -0.363708
Excess_kurtosis             -0.214491  0.791591
Skewness                    -0.204782  0.709528
Mean_dmsnr                  -0.354269  0.400876
Std_deviation_dmsnr         -0.575800  0.491535
Excess_kurtosis_dmsnr        0.923743 -0.390816
Skewness_dmsnr               1.000000 -0.259117
Class                       -0.259117  1.000000